version: "3"

services:
  rproxy:
    image: nginx:alpine
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:8080"
    volumes:
      - ./rproxy/nginx.conf:/etc/nginx/nginx.conf

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
        - db
    environment:
      MARIA_DB: root:password@tcp(db:3306)/fabulous-fox
    
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: 'fabulous-fox'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - my-db:/data/mysql
      - ./db/prod:/docker-entrypoint-initdb.d

volumes:
  my-db: