version: "3"

services:
  rproxy:
    image: nginx:alpine
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:8080"
    volumes:
      - ./rproxy/nginx.conf:/etc/nginx/nginx.conf

  frontend:
    build:
      context: ./client

  backend:
    build:
      context: ./server
    depends_on:
        - db
  
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: 'fabulous-fox'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/data/mysql
      - ./db/prod:/docker-entrypoint-initdb.d

volumes:
  my-db: