version: "3"

services:
  frontend:
    container_name: frontend_unit_tests
    build:
      context: ./client
      dockerfile: Dockerfile_unit
  db:
    image: mariadb
    container_name: db_unit_tests
    environment:
      MYSQL_DATABASE: 'fabulous-fox-test'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user1'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    command: --init-file /data/application/init.sql
    volumes:
      - ./db/test/init.sql:/data/application/init.sql
     
  backend:
    container_name: backend_unit_tests
    depends_on:
      - db
    build:
      context: ./server
      dockerfile: Dockerfile_unit
    environment:
      MARIA_DB: root:password@tcp(db:3306)/fabulous-fox-test 
